FROM node:latest

LABEL authors="santiago"
WORKDIR /opt/user


COPY killmepls/package*.json ./

RUN npm install axios@1.7.5 next@14.2.6 react-dom@18.3.1 react-icons@5.3.0 react@18.3.1 sass@1.77.8

COPY killmepls . 

EXPOSE 3000

CMD ["npm", "run", "dev"]
